# Generated by Django 4.0.4 on 2022-06-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Clothes', 'Clothes')], default='Clothes', max_length=100),
        ),
    ]
