# Generated by Django 4.0.4 on 2022-06-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
    ]
